#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern "C" void _ALU_reg(void);
extern "C" void _CaDynamics_DC0_reg(void);
extern "C" void _CaDynamics_E2_reg(void);
extern "C" void _Ca_HVA2_reg(void);
extern "C" void _Ca_HVA_reg(void);
extern "C" void _Ca_LVAst_reg(void);
extern "C" void _Ca_reg(void);
extern "C" void _conductanceSource_reg(void);
extern "C" void _CoreNEURONArtificialCell_reg(void);
extern "C" void _DetAMPANMDA_reg(void);
extern "C" void _DetGABAAB_reg(void);
extern "C" void _gap_reg(void);
extern "C" void _GluSynapse_reg(void);
extern "C" void _HDF5reader_reg(void);
extern "C" void _Ih_reg(void);
extern "C" void _Im_reg(void);
extern "C" void _KdShu2007_reg(void);
extern "C" void _K_Pst_reg(void);
extern "C" void _K_Tst_reg(void);
extern "C" void _Kv7_reg(void);
extern "C" void _Nap_Et2_reg(void);
extern "C" void _NaTa_t_reg(void);
extern "C" void _NaTg_axon_reg(void);
extern "C" void _NaTg_reg(void);
extern "C" void _NaTg_persistent_axon_reg(void);
extern "C" void _NaTg_persistent_somadend_reg(void);
extern "C" void _NaTg_somadend_reg(void);
extern "C" void _NaTs2_t_reg(void);
extern "C" void _netstim_inhpoisson_reg(void);
extern "C" void _ProbAMPANMDA_EMS_reg(void);
extern "C" void _ProbGABAAB_EMS_reg(void);
extern "C" void _SK_E2_reg(void);
extern "C" void _SKv3_1_reg(void);
extern "C" void _SonataReportHelper_reg(void);
extern "C" void _SonataReports_reg(void);
extern "C" void _StochKv3_reg(void);
extern "C" void _StochKv_reg(void);
extern "C" void _TTXDynamicsSwitch_reg(void);
extern "C" void _VecStim_reg(void);

extern "C" void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"mod/ALU.mod\"");
    fprintf(stderr, " \"mod/CaDynamics_DC0.mod\"");
    fprintf(stderr, " \"mod/CaDynamics_E2.mod\"");
    fprintf(stderr, " \"mod/Ca_HVA2.mod\"");
    fprintf(stderr, " \"mod/Ca_HVA.mod\"");
    fprintf(stderr, " \"mod/Ca_LVAst.mod\"");
    fprintf(stderr, " \"mod/Ca.mod\"");
    fprintf(stderr, " \"mod/conductanceSource.mod\"");
    fprintf(stderr, " \"mod/CoreNEURONArtificialCell.mod\"");
    fprintf(stderr, " \"mod/DetAMPANMDA.mod\"");
    fprintf(stderr, " \"mod/DetGABAAB.mod\"");
    fprintf(stderr, " \"mod/gap.mod\"");
    fprintf(stderr, " \"mod/GluSynapse.mod\"");
    fprintf(stderr, " \"mod/HDF5reader.mod\"");
    fprintf(stderr, " \"mod/Ih.mod\"");
    fprintf(stderr, " \"mod/Im.mod\"");
    fprintf(stderr, " \"mod/KdShu2007.mod\"");
    fprintf(stderr, " \"mod/K_Pst.mod\"");
    fprintf(stderr, " \"mod/K_Tst.mod\"");
    fprintf(stderr, " \"mod/Kv7.mod\"");
    fprintf(stderr, " \"mod/Nap_Et2.mod\"");
    fprintf(stderr, " \"mod/NaTa_t.mod\"");
    fprintf(stderr, " \"mod/NaTg_axon.mod\"");
    fprintf(stderr, " \"mod/NaTg.mod\"");
    fprintf(stderr, " \"mod/NaTg_persistent_axon.mod\"");
    fprintf(stderr, " \"mod/NaTg_persistent_somadend.mod\"");
    fprintf(stderr, " \"mod/NaTg_somadend.mod\"");
    fprintf(stderr, " \"mod/NaTs2_t.mod\"");
    fprintf(stderr, " \"mod/netstim_inhpoisson.mod\"");
    fprintf(stderr, " \"mod/ProbAMPANMDA_EMS.mod\"");
    fprintf(stderr, " \"mod/ProbGABAAB_EMS.mod\"");
    fprintf(stderr, " \"mod/SK_E2.mod\"");
    fprintf(stderr, " \"mod/SKv3_1.mod\"");
    fprintf(stderr, " \"mod/SonataReportHelper.mod\"");
    fprintf(stderr, " \"mod/SonataReports.mod\"");
    fprintf(stderr, " \"mod/StochKv3.mod\"");
    fprintf(stderr, " \"mod/StochKv.mod\"");
    fprintf(stderr, " \"mod/TTXDynamicsSwitch.mod\"");
    fprintf(stderr, " \"mod/VecStim.mod\"");
    fprintf(stderr, "\n");
  }
  _ALU_reg();
  _CaDynamics_DC0_reg();
  _CaDynamics_E2_reg();
  _Ca_HVA2_reg();
  _Ca_HVA_reg();
  _Ca_LVAst_reg();
  _Ca_reg();
  _conductanceSource_reg();
  _CoreNEURONArtificialCell_reg();
  _DetAMPANMDA_reg();
  _DetGABAAB_reg();
  _gap_reg();
  _GluSynapse_reg();
  _HDF5reader_reg();
  _Ih_reg();
  _Im_reg();
  _KdShu2007_reg();
  _K_Pst_reg();
  _K_Tst_reg();
  _Kv7_reg();
  _Nap_Et2_reg();
  _NaTa_t_reg();
  _NaTg_axon_reg();
  _NaTg_reg();
  _NaTg_persistent_axon_reg();
  _NaTg_persistent_somadend_reg();
  _NaTg_somadend_reg();
  _NaTs2_t_reg();
  _netstim_inhpoisson_reg();
  _ProbAMPANMDA_EMS_reg();
  _ProbGABAAB_EMS_reg();
  _SK_E2_reg();
  _SKv3_1_reg();
  _SonataReportHelper_reg();
  _SonataReports_reg();
  _StochKv3_reg();
  _StochKv_reg();
  _TTXDynamicsSwitch_reg();
  _VecStim_reg();
}
